### ISSUE TITLE
Nonfunctional mod due to content mismatch

### ISSUE THREAD

**Issue by ghost** [Mengmoshu/Resource_Relocation_Machines#11]
I initially got an error about info.json not being around. Factorio treats the zip itself as the folder, making having the zipped file be everything in one folder not only redundant but breaking.

But this isn't the reason for the issue at hand. After unzipping the mod to try and get it to work, I get another crashing error: Path _ _Resource_Relocation_Machine_ _/graphics/Range10-Active-E.png does not match any mod. (I had to add spaces, as otherwise it comes out boldface here) From the looks of things the mod is looking for the folder/file "Resource Relocation Machine" and not "Resource_Relocation_Machines_0.0.5" the former of which of course doesn't exist. I can't change the folder either as that causes another mismatch elsewhere. The mod expects to be named "Resource_Relocation_Machines_0.0.5". This causes the mod to be fully unplayable as it is, to the point that I can't even start with it. Looking at the lua code shows that this mismatch is everywhere in the mod, suggesting that the "s_0.0.5" was tacked on at the last minute and not even tested to see if it breaks something.

Such carelessness at the very end is a real shame, as I'm sure the mod could have had a lot of use if it, you know, worked.

**Comment by Mengmoshu** [comment]
Thanks for letting me know. If I'd updated the version I'm playing with I would have caught it. I changed the name slightly (just pluralized it) and didn't check all the places it matters. I'll get a fixed version up ASAP.

**Comment by Mengmoshu** [comment]
Alright. I've uploaded the fixed version to the Mod Portal so if you've still got a copy of the mod you can just use the Update Mods button in-game.

For the Record: Closed by #12
