### ISSUE TITLE
not really an issue just trying to contact you

### ISSUE THREAD

**Issue by dutchuss2016** [Mengmoshu/Resource_Relocation_Machines#17]
Hi I noticed you haven't updated the mod for 0.17 i have downloaded the v 16 version and got it working with v 0.17 and would like either to submit my changes to you so you can send them to the mod portal or permission to re upload my own branch of the mod to keep updated will credit you for the original work just this mod is one of my quality of life mods because i hate building on ore patches please contact me back and let me know either way

**Comment by Mengmoshu** [comment]
I'm glad you like it. If you submit a Pull Request I'll review it. Try to keep any changes in that Pull Request to *only* what is needed to make it work in 0.17. If I don't find any problems with your update I'll get it uploaded to the mod portal as soon as I can.

If you need help figuring out how to do a pull request beyond what you can find using Google, the r/Factorio Discord's #programming and #mod-making channels have a lot of people who can probably help.

I'll leave this issue open for now.

**Comment by dutchuss2016** [comment]
i have posted the pull request for you would be intrested in trying to do some graphics for youfor this mod if you would like them i have the free time

**Comment by dutchuss2016** [comment]
![image](https://user-images.githubusercontent.com/32156904/59952072-94fdf580-9440-11e9-8214-bf40f5474d24.png)

**Comment by dutchuss2016** [comment]
i see you merged let me know if you would like me to come up with some graphic drafts and ill get started on that

**Comment by Mengmoshu** [comment]
Yup. Gonna add you to the author list, and maybe put something in the readme, then I'll package it up and upload. Do you want to be credited as dutchuss2016, or another name?

Graphics would be very welcome. My crappy programmer art needs to be retired.

**Comment by dutchuss2016** [comment]
my in-game name is Vampiredmage if you wouldn't mind

**Comment by dutchuss2016** [comment]
can you create another branch for graphics testing purposes?

**Comment by Mengmoshu** [comment]
Done. If you use Discord I'm on there basically all the time as Mengmoshu#0003

**Comment by dutchuss2016** [comment]
as in your discord tag is @#3

**Comment by Mengmoshu** [comment]
And I might have left a slight mess on the graphics branch, but it should be easy to resolve whenever you're done. And that part would be my problem anyway.

**Comment by Mengmoshu** [comment]
Sorry, GitHub butchered it. `Mengmoshu` and my discriminator is `0003`

**Comment by dutchuss2016** [comment]
#thanksgithub

**Comment by dutchuss2016** [comment]
im gonna do some local testing with some graphics ideas before i pull request them (or do i have direct access to the graphics branch?

**Comment by Mengmoshu** [comment]
I think you'll need to fork that branch, and do a PR. I'm going to close this issue though, now that we're talking on Discord.
