### ISSUE TITLE
Mining a mover entity always gives tier 1

### ISSUE THREAD

**Issue by Zaflis** [Mengmoshu/Resource_Relocation_Machines#25]
I know this is in the mod description page, but i think i know how to fix it.
prototypes\entities.lua, line 10:

temp.minable = {hardness = 0.1, mining_time = 0.1, result = "rrm-range10"}

Replace with:

temp.minable = {hardness = 0.1, mining_time = 0.1, result = "rrm-range" .. inputs.range}

**Comment by Mengmoshu** [comment]
This is already *working as designed*. I personally like having them return to the shorter range when mined, and it costs no materials to craft them to a higher range. If they only returned the same range item every time then each time you wanted a shorter range again you would have to craft more.

I have plans to provide an option for it to work differently, but implementing that will take more work than I've been interested in doing. Many people seem to think this is a bug, and I'd like to support the way they'd like the mod to work without abandoning the way I want it to work.
