### ISSUE TITLE
Resource stack

### ISSUE THREAD

**Issue by Rotn240** [Mengmoshu/Resource_Relocation_Machines#29]
As title says would you consider adding such a feature when it has reached it's range limit it will move each tile of ore the same way as it already does but just add that to the existing ones infront of it's self  if you get my meaning or in some other way it's up to you that's something i would like to love this mod even more

I use this to make the patches square-ich and to split mixed ore apart from each other i would love such a fearture

Regards
Discord: Rotn_#9961

**Comment by Mengmoshu** [comment]
I've got plans for a different machine that will merge two ore entities, so I'm not sure how much I like adding functionality like that to the basic Resource Relocation Machine.

You might see some ideas you like if you look at the list of open issues. #3 , #4 , and #5 especially seem like things you'd use. Though I do have to mention that I've mostly only been doing just enough work on this mod to keep it working with new versions of Factorio.

**Comment by Rotn240** [comment]
alright i'll keep my eyes open for that and i'll take a look at the other issues you mentioned
